### ISSUE TITLE
help in some simulation 

### ISSUE THREAD

**Issue by ashraf590** [AdityaVaradaraj/Robust-Control-of-Bevel-Tipped-Needle#1]
dear dr,
i want ask you in som help in simulation of SMC if you would.
thanks.

**Comment by AdityaVaradaraj** [comment]
Hi. I am a Masters Student. Not a dr. Anyways... for simulation of SMC, you can use ode45 solver in MATLAB and then in the function having the differential equations,  calculate the sliding variable from the states and use that to calculate control input and then use that in equation for the derivatives of state.

**Comment by ashraf590** [comment]
Hey thanks for your response
I have to simulate a paper in smc as assignment
So can you help me
Thanx

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AdityaVaradaraj** [comment]
If you can tell what issue you are facing, I can try to explain

**Comment by ashraf590** [comment]
can i attach you a paper and the code i have implemented tell now

**Comment by AdityaVaradaraj** [comment]
Sorry I can't go into detail as it is your assignment. But if you can tell me what the problem you are facing in general is, I can try to help out.

**Comment by ashraf590** [comment]
i face a problem to implement sliding mode observer defferintiator

**Comment by ashraf590** [comment]
thank you at all

**Comment by AdityaVaradaraj** [comment]
> Hi. I am a Masters Student. Not a dr. Anyways... for simulation of SMC, you can use ode45 solver in MATLAB and then in the function having the differential equations, calculate the sliding variable from the states and use that to calculate control input and then use that in equation for the derivatives of state.

I don't think I can help anymore than what I have outlined here.
